atmospheric_model:
  complexity: basic
  enabled: true
  include_cloud_layers: true
celestial_bodies:
- sun
- moon
- mercury
- venus
- earth
- mars
- jupiter
- saturn
- uranus
- neptune
create_plots: true
location:
  elevation: 0
  latitude: 40.7127281
  longitude: -74.0060152
  name: City of New York, New York, United States
output_file: data/venus_data.csv
real_time: false
tracking_interval: 10
visualization:
  plot_3d_position: true
  plot_altitude_azimuth: true
  plot_temperature: true
